"""
Module containing constants for the day 2 puzzle
"""
ROCK = 1
PAPER = 2
SCISSORS = 3
LOSE = 0
DRAW = 3
WIN = 6
ELF_ROCK = 'A'
ELF_PAPER = 'B'
ELF_SCISSORS = 'C'
ME_ROCK = 'X'
ME_PAPER = 'Y'
ME_SCISSORS = 'Z'
RULES = {
    (ELF_ROCK, ME_ROCK): DRAW + ROCK,
    (ELF_ROCK, ME_PAPER): WIN + PAPER,
    (ELF_ROCK, ME_SCISSORS): LOSE + SCISSORS,
    (ELF_PAPER, ME_ROCK): LOSE + ROCK,
    (ELF_PAPER, ME_PAPER): DRAW + PAPER,
    (ELF_PAPER, ME_SCISSORS): WIN + SCISSORS,
    (ELF_SCISSORS, ME_ROCK): WIN + ROCK,
    (ELF_SCISSORS, ME_PAPER): LOSE + PAPER,
    (ELF_SCISSORS, ME_SCISSORS): DRAW + SCISSORS
}
